inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true

Layout/IndentationWidth:
  Description: 'Use 2 spaces for indentation.'

Layout/CaseIndentation:
  Description: 'Indentation of when in a case/when/[else/]end.'

Style/HashSyntax:
  Description: 'Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax'
  EnforcedStyle: ruby19

Style/FrozenStringLiteralComment:
  Include:
  - 'app/**/*.rb'
  - 'lib/**/*.rb'
  Enabled: false

Metrics/LineLength:
  Description: 'Limit lines to 100 characters.'
  Max: 101
  Enabled: false
