AllCops:
  TargetRubyVersion: 2.5
  DisabledByDefault: true

#################### Layout ###############################

Layout/AccessModifierIndentation:
  Description: Check indentation of private/protected visibility modifiers.
  StyleGuide: '#indent-public-private-protected'
  Enabled: true

Layout/InitialIndentation:
  Description: >-
    Checks the indentation of the first non-blank non-comment line in a file.
  Enabled: true

Layout/IndentationWidth:
  Description: "Use 2 spaces for indentation."
  StyleGuide: "#spaces-indentation"
  Enabled: true

Layout/IndentationConsistency:
  Description: 'Keep indentation straight.'
  StyleGuide: '#spaces-indentation'
  Enabled: true

Layout/CaseIndentation:
  Description: "Indentation of when in a case/when/[else/]end."
  StyleGuide: "#indent-when-to-case"
  Enabled: true

Layout/ElseAlignment:
  Description: 'Align elses and elsifs correctly.'
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Description: "Keep blank lines around access modifiers."
  StyleGuide: "#empty-lines-around-access-modifier"
  Enabled: true

Layout/EndAlignment:
  Description: 'Align ends correctly.'
  Enabled: true

Layout/EndOfLine:
  Description: "Use Unix-style line endings."
  StyleGuide: "#crlf"
  Enabled: true

Layout/ExtraSpacing:
  Description: "Do not use unnecessary spacing."
  Enabled: true

Layout/LeadingCommentSpace:
  Description: "Comments should start with a space."
  StyleGuide: "#hash-space"
  Enabled: true

Layout/SpaceAfterColon:
  Description: "Use spaces after colons."
  StyleGuide: "#spaces-operators"
  Enabled: true

Layout/SpaceAfterComma:
  Description: "Use spaces after commas."
  StyleGuide: '#spaces-operators'
  Enabled: true

Layout/SpaceAfterMethodName:
  Description: >-
                 Do not put a space between a method name and the opening
                 parenthesis in a method definition.
  StyleGuide: "#parens-no-spaces"
  Enabled: true

Layout/SpaceAfterNot:
  Description: Tracks redundant space after the ! operator.
  StyleGuide: "#no-space-bang"
  Enabled: true

Layout/SpaceAfterSemicolon:
  Description: "Use spaces after semicolons."
  StyleGuide: '#spaces-operators'
  Enabled: true

Layout/SpaceBeforeComma:
  Description: "No spaces before commas."
  Enabled: true

Layout/SpaceBeforeComment:
  Description: >-
                 Checks for missing space between code and a comment on the
                 same line.
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Description: "No spaces before semicolons."
  Enabled: true

Layout/SpaceAroundOperators:
  Description: "Use a single space around operators."
  StyleGuide: "#spaces-operators"
  Enabled: true

Layout/Tab:
  Description: "No hard tabs."
  StyleGuide: "#spaces-indentation"
  Enabled: true

Layout/TrailingBlankLines:
  Description: "Checks trailing blank lines and final newline."
  StyleGuide: '#newline-eof'
  Enabled: true

Layout/TrailingWhitespace:
  Description: "Avoid trailing whitespace."
  StyleGuide: "#no-trailing-whitespace"
  Enabled: true

#################### Naming ##############################

Naming/ClassAndModuleCamelCase:
  Description: "Use CamelCase for classes and modules."
  StyleGuide: "#camelcase-classes"
  Enabled: true

Naming/ConstantName:
  Description: "Constants should use SCREAMING_SNAKE_CASE."
  StyleGuide: "#screaming-snake-case"
  Enabled: true

#################### Style ###############################

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  StyleGuide: '#namespace-definition'
  Enabled: true
  EnforcedStyle: nested

Style/ClassVars:
  Description: 'Avoid the use of class variables.'
  StyleGuide: '#no-class-vars'
  Enabled: true

Style/DefWithParentheses:
  Description: "Use def with parentheses when there are arguments."
  StyleGuide: "#method-parens"
  Enabled: true

Style/Encoding:
  Description: "Use UTF-8 as the source file encoding."
  StyleGuide: "#utf-8"
  Enabled: true

Style/FrozenStringLiteralComment:
  Description: "Add frozen_string_literal comment to the top of files"
  Include:
  - "app/**/*.rb"
  - "lib/**/*.rb"
  Enabled: true

Style/HashSyntax:
  Description: "Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax { :a => 1, :b => 2}"
  EnforcedStyle: ruby19

Style/IfInsideElse:
  Description: "Finds if nodes inside else, which can be converted to elsif."
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Description: "Do not use parentheses for method calls with no arguments."
  StyleGuide: "#method-invocation-parens"
  Enabled: true

Style/MethodDefParentheses:
  Description: >-
                 Checks if the method definitions have or don't have
                 parentheses.
  StyleGuide: "#method-parens"
  Enabled: true

Style/RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: true

Style/RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: true

Style/TrailingCommaInArguments:
  Description: "Checks for trailing comma in argument lists."
  StyleGuide: "#no-trailing-params-comma"
  Enabled: true

#################### Metrics ###############################

# TODO
Metrics/LineLength:
  Description: "Limit lines to 80 characters."
  StyleGuide: "#80-character-limits"
  Enabled: false


#################### Bundler ###############################

Bundler/DuplicatedGem:
  Description: "Checks for duplicate gem entries in Gemfile."
  Enabled: true
  Include:
    - "**/Gemfile"
    - "**/gems.rb"
