inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true

Style/HashSyntax:
  EnforcedStyle: ruby19

# Gonna add this later...
# Style/FrozenStringLiteralComment:
#   Include:
#   - 'app/**/*.rb'
#   - 'lib/**/*.rb'
