AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true

Layout/IndentationWidth:
  Description: "Use 2 spaces for indentation."

Layout/CaseIndentation:
  Description: "Indentation of when in a case/when/[else/]end."

Layout/TrailingWhitespace:
  Description: "Avoid trailing whitespace."
  Enabled: true

Style/HashSyntax:
  Description: "Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax"
  EnforcedStyle: ruby19

# TODO
Style/FrozenStringLiteralComment:
  Description: "Add frozen_string_literal comment to the top of files"
  Include:
  - "app/**/*.rb"
  - "lib/**/*.rb"
  Enabled: false

Style/RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: true

# TODO
Metrics/LineLength:
  Description: "Limit lines to 100 characters."
  Max: 101
  Enabled: false
