AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: true

Layout/IndentationWidth:
  Description: "Use 2 spaces for indentation."
  StyleGuide: "#spaces-indentation"
  Enabled: true

Layout/CaseIndentation:
  Description: "Indentation of when in a case/when/[else/]end."
  StyleGuide: "#indent-when-to-case"
  Enabled: true

Layout/TrailingWhitespace:
  Description: 'Avoid trailing whitespace.'
  StyleGuide: '#no-trailing-whitespace'
  Enabled: true

Style/DefWithParentheses:
  Description: "Use def with parentheses when there are arguments."
  StyleGuide: "#method-parens"
  Enabled: true

Style/HashSyntax:
  Description: "Prefer Ruby 1.9 hash syntax { a: 1, b: 2 } over 1.8 syntax"
  EnforcedStyle: ruby19

# TODO
Style/FrozenStringLiteralComment:
  Description: "Add frozen_string_literal comment to the top of files"
  Include:
  - "app/**/*.rb"
  - "lib/**/*.rb"
  Enabled: false

Style/RedundantReturn:
  Description: "Don't use return where it's not required."
  Enabled: true

Style/RedundantSelf:
  Description: "Don't use self where it's not needed."
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Description: "Do not use parentheses for method calls with no arguments."
  StyleGuide: "#method-invocation-parens"
  Enabled: true

Style/MethodDefParentheses:
  Description: >-
                 Checks if the method definitions have or don't have
                 parentheses.
  StyleGuide: "#method-parens"
  Enabled: true

Style/TrailingCommaInArguments:
  Description: "Checks for trailing comma in argument lists."
  StyleGuide: "#no-trailing-params-comma"
  Enabled: true

# TODO
Metrics/LineLength:
  Description: "Limit lines to 80 characters."
  StyleGuide: "#80-character-limits"
  Enabled: true
